title: Before lights out
author: Rahul Sreenivasan
email: rahulsreenivasan.rs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Inside the garage, the minds of the drivers
  Behind the pit walls and development centers 
  Let's explore what happens before and after lights out 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minimal
